ช่วยตรวจงานให้ผมหน่อยนะครับ /ขอบคุณครับ @Guide to bodybuilders
saturday-js/saturday-homework pull request #14
Opened 2017-10-24 11:53 UTC by nuttakit2405

2017-10-24 15:26 UTC, pangaunn requested changes
แก้ conflict มาด้วยนะ

2017-10-24 15:28 UTC, n9ti requested changes
แก้มาด้วยครับ
โดยเฉพาะ bootstrap ผมบอกไปแล้วว่าไม่ให้ใช้
ลองไปหัดใช้ Bulma ดูครับ

2017-10-24 15:28 UTC, n9ti commented on index.html
> +    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin
ให้ใช้ bulma แทนครับ 
ไม่เอา bootstrap

2017-10-24 15:28 UTC, n9ti commented on index.html
> +    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
ไม่ให้ใช้ jQuery ครับ

2017-10-24 15:28 UTC, n9ti commented on index.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></scr
ให้ใช้ bulma แทนครับ
ไม่เอา bootstrap

2017-10-24 15:28 UTC, n9ti commented on src/components/Nati.vue
> -
มาแก้อะไรไฟล์นี้ครับ เอากลับให้เหมือนเดิมด้วยครับ

2017-10-24 15:28 UTC, n9ti commented on src/components/Nuttakit.vue
> +    <div class="columns">
คุณก็ใช้ class ของ bulma แต่ไปติดตั้ง bootstrap ทำไม?

2017-10-24 15:28 UTC, n9ti commented on src/components/Nuttakit.vue
> +              <a :href="`//en.wikipedia.org/wiki/${result.name}`" target="_blank">
ข้อมูลซ้ำกันพวกนี้ทำไมไม่เอาไปเก็บใน json แล้วใช้ v-for วนดึงค่าออกมาแสดงเอาครับ

2017-10-25 03:40 UTC, pangaunn requested changes
ยังมี conflict อยู่เลยครับ

2017-10-25 06:20 UTC, kingkong64 commented
@nuttakit2405  hey dude ยังมี conflict อยู่เลย

2017-10-26 03:45 UTC, n9ti requested changes
แก้ตามที่ Comment เพิ่มไปด้วยนะครับ

2017-10-26 03:45 UTC, n9ti commented on src/App.vue
>      <section class="section">
มายุ่งอะไรไฟล์นี้ มันกระทบคนอื่นเค้าครับ เอากลับให้เหมือนเดิมด้วยครับ

2017-10-26 03:45 UTC, n9ti commented on src/App.vue
> +  }
เอาตรงนี้ออกไปด้วยครับ

2017-10-26 07:07 UTC, merged