API Movies is Coming
saturday-js/saturday-homework pull request #7
Opened 2017-10-23 17:00 UTC by flamezaxaou10

2017-10-23 17:04 UTC, n9ti commented
แก้ conflicts ด้วยครับ

2017-10-23 17:22 UTC, flamezaxaou10 commented
fix conflicts

2017-10-23 18:10 UTC, n9ti requested changes
ถ้าเพิ่ม Search มาด้วยจะดีมาก

2017-10-23 18:10 UTC, n9ti commented on src/components/Sillawat.vue
> +      isLoading: true
isLoading  มีไว้ทำไม ถ้าไม่ได้ใช้

2017-10-23 18:10 UTC, n9ti commented on src/components/Sillawat.vue
> +        this.isLoading = false
isLoading มีไว้ทำไม ถ้าไม่ได้ใช้

2017-10-23 18:15 UTC, flamezaxaou10 commented
search ที่ไม่ทำเพราะว่า หนังที่จะเข้าใหม่ มันมีน้อยครับ

2017-10-23 18:17 UTC, n9ti commented
งั้นทำ filter ให้แบ่ง ประเภทของหนังได้ไหม
[All] [Action] [Drama] [Cartoon] [.....]

2017-10-23 18:18 UTC, n9ti commented
ส่วน isLoading ไหนๆก็มีแล้ว ก็ทำให้มันมี loading ดีๆไปเลยก็ได้นะ

2017-10-23 18:20 UTC, n9ti commented
มันพังอยู่ด้วยนะ
https://travis-ci.org/saturday-js/saturday-homework/builds/291681518

2017-10-24 02:59 UTC, pangaunn requested changes
แก้ conflict ด้วยครับ

2017-10-24 17:02 UTC, flamezaxaou10 commented
แก้ให้แล้วครับ

2017-10-24 17:20 UTC, flamezaxaou10 commented
ส่งงานครับ

2017-10-25 03:39 UTC, pangaunn approved these changes

2017-10-25 04:38 UTC, merged